// This file is auto-generated by scripts/sync-wood-species.mjs
// Do not edit manually — run `node scripts/sync-wood-species.mjs` to regenerate.
// Last synced: 2026-06-10T15:29:22.728Z

export interface SpeciesPhoto {
  fileId: string
  name: string
  width: number | null
  height: number | null
}

export interface WoodSpecies {
  name: string
  slug: string
  coverImage: string | null
  photoCount: number
  driveFileIds: SpeciesPhoto[]
  varieties: WoodSpecies[]
}

export const woodSpeciesData: WoodSpecies[] = [
  {
    "name": "Alder",
    "slug": "alder",
    "coverImage": "/images/wood-species/alder-cover.png",
    "photoCount": 2,
    "driveFileIds": [
      {
        "fileId": "1bfc0UoK_hzbQs3jJfs7iiQx-1fE7c03t",
        "name": "Alder Dining Table (3).png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1WMmqZpgFb82vV9CMlaS4JPpNIoi_F1Mz",
        "name": "Alder Dining Table (1).png",
        "width": 1512,
        "height": 2016
      }
    ],
    "varieties": []
  },
  {
    "name": "Ash",
    "slug": "ash",
    "coverImage": "/images/wood-species/ash-cover.jpg",
    "photoCount": 1,
    "driveFileIds": [
      {
        "fileId": "1lL1BHCJSPXSA3R8S0IDCruEYm6dvF-A5",
        "name": "Ash.jpg",
        "width": 3611,
        "height": 2610
      }
    ],
    "varieties": []
  },
  {
    "name": "Birch",
    "slug": "birch",
    "coverImage": "/images/wood-species/birch-cover.jpg",
    "photoCount": 4,
    "driveFileIds": [
      {
        "fileId": "1G5EudjW1KsfdUBTeaIsXO-Tn6eztJBvV",
        "name": "Red birch 48 x 28 cocktail blue green duo Xeni leg.jpg",
        "width": 768,
        "height": 1024
      },
      {
        "fileId": "1zvdVMTGXQ0fWxoDeKQVXcQJvK2qRmtEB",
        "name": "Red Birch Double River Pearl Black .jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "1EngQMlhQAbKeSluMClLq-wSrybqCnbnt",
        "name": "Red Birch Double River Pearl Black .jpg",
        "width": 481,
        "height": 640
      },
      {
        "fileId": "1Wd0VHgQWQ0eEJWx26H7SQDNcnP-LzxNf",
        "name": "Red Birch Ocean.jpg",
        "width": 683,
        "height": 911
      }
    ],
    "varieties": []
  },
  {
    "name": "Black Locust",
    "slug": "black-locust",
    "coverImage": "/images/wood-species/black-locust-cover.jpg",
    "photoCount": 3,
    "driveFileIds": [
      {
        "fileId": "1LVQOr-qMpCJqp5eUFCgscQIw4tnSGCDm",
        "name": "Black Locust NH RR.jpg",
        "width": 335,
        "height": 564
      },
      {
        "fileId": "12b32qsQQbk5fSMm-qX1xbhR2_2KURh7-",
        "name": "Black Locust Waterfall coffee table.png",
        "width": 1227,
        "height": 920
      },
      {
        "fileId": "1OiMAOmaXYaCJ5t53aK92r19Z9e1i_V0a",
        "name": "Black Locust Sunapee.JPG",
        "width": 4032,
        "height": 3024
      }
    ],
    "varieties": []
  },
  {
    "name": "Black Walnut",
    "slug": "black-walnut",
    "coverImage": "/images/wood-species/black-walnut-cover.jpg",
    "photoCount": 51,
    "driveFileIds": [
      {
        "fileId": "1G7pd2VMxX1PvhJN9vFTGXIEkpv_c1UyV",
        "name": "Black Walnut Console with Carolina Blue 3d.jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "1tg9F4Tz4HDOBrvZkR4DEkm6_d9KtlIQM",
        "name": "Black Walnut live edge custom with CNC carving.png",
        "width": 696,
        "height": 928
      },
      {
        "fileId": "1fkN2Jj2sAoJpTv0Kl__Q7asHQP6WqOuY",
        "name": "Black Walnut Slab with Red Smoke.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1h3nXpx65h-huQCtsG7KfqmCyOfCi5kZk",
        "name": "Black Walnut Antique Copper 3D.jpg",
        "width": 440,
        "height": 783
      },
      {
        "fileId": "14C1c08fY3NA7Q2FGV9VXNXVZ5YALSBM2",
        "name": "Black Walnut RR Slab Base.jpg",
        "width": 1012,
        "height": 809
      },
      {
        "fileId": "1iZ1w6119-z4oZUxIA50EJF_cV-3WwAYE",
        "name": "Black Walnut Pacific Blue.jpg",
        "width": 1215,
        "height": 911
      },
      {
        "fileId": "16M_OVhQAMoyRhvODBtkp5wArt6TIld4F",
        "name": "Black Walnut Ocean.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1fRA3oRSwpF1Y8AtyTCYow46m0pOfv9dP",
        "name": "BW Picnic Rustic Live Edge.JPG",
        "width": 1260,
        "height": 945
      },
      {
        "fileId": "1i_YGmnS5Kj5IuUAHsDXyIIv7TXWdQqXr",
        "name": "BW with Black River Straight Edges.jpeg",
        "width": 1215,
        "height": 911
      },
      {
        "fileId": "15dV1a1yZP00C3xo7nDFea8RvDQKcPwK8",
        "name": "Black Walnut Ocean Conference with logo.jpg",
        "width": 664,
        "height": 911
      },
      {
        "fileId": "1Jgcyv6LwziLJWGATQvGnEYgFO2sSoE-2",
        "name": "Black Walnut on Trapezoid Base.png",
        "width": 1252,
        "height": 939
      },
      {
        "fileId": "1UcjJS1pd9QEar3H8zDH8pSTjpLSLXRkd",
        "name": "Black Walnut Waterfall with Silver.png",
        "width": 1238,
        "height": 928
      },
      {
        "fileId": "1-5T5XdE8i0Pi2hlFI_gDQhpWTS0rJqF5",
        "name": "Black Walnut on Sewing Machine Base.png",
        "width": 802,
        "height": 537
      },
      {
        "fileId": "1Mj0pkDhH1N_Qy7picaYj18Ab0CuUie1O",
        "name": "BW with Baku Red Conference.png",
        "width": 1303,
        "height": 977
      },
      {
        "fileId": "1whyLxbkksbmSo1dn6bQupm4fgG4e7CVa",
        "name": "Black Walnut Bar Top.png",
        "width": 1238,
        "height": 928
      },
      {
        "fileId": "1bixTP0vkHzkCtHi_l_QOpEHez2DYJAgh",
        "name": "Black Walnut Pacific Blue Wave.png",
        "width": 1238,
        "height": 928
      },
      {
        "fileId": "1smQkHYxxST5wRSuBuYqogRsQCPsTRsu3",
        "name": "BW Antique Copper Fill.png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1Qj-7ro0I0aeIe8C3DU3pGm2JG0Gxu9w9",
        "name": "Black Walnut Antique Copper Fill.png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1c1CLUL-bdiwQw0xAD6_5KBTM93-OSgr4",
        "name": "Black Walnut Merlot Rivers.png",
        "width": 1303,
        "height": 977
      },
      {
        "fileId": "1NH8dvUhUf03d_3KJAQU_5vNA_gbFz1ud",
        "name": "Black Walnut RR on Pacific Blue.png",
        "width": 690,
        "height": 920
      },
      {
        "fileId": "1BU_SM9bMEQM_ihZqV6SyUTGC8RBiNgxq",
        "name": "Black Walnut Pacific Blue.jpg",
        "width": 1219,
        "height": 856
      },
      {
        "fileId": "1qQF2mJLZ1RhUlbPVaJsgNNZNlDywsq_d",
        "name": "Black Walnut with Black Soft Live Edge.jpeg",
        "width": 686,
        "height": 911
      },
      {
        "fileId": "1OiSz-b5T_rLtOVRFeHs-u9jb2maYd9vn",
        "name": "Black Walnut Deep Ocean Green.jpeg",
        "width": 686,
        "height": 911
      },
      {
        "fileId": "18V8r9aWhBriV7E1QcNDNos6PpttbYeo9",
        "name": "Black Walnut with Black FP Fill.jpeg",
        "width": 686,
        "height": 911
      },
      {
        "fileId": "1CMQHetxa5_V-V6N8DS8k2kAzgxoXnt2W",
        "name": "Black Walnut with Black FP Fill.jpeg",
        "width": 686,
        "height": 911
      },
      {
        "fileId": "1aWkSirRA8KaDu6BGVQAF9Kh5HbVrM2Ei",
        "name": "BW RR Pac Blue.jpg",
        "width": 640,
        "height": 480
      },
      {
        "fileId": "1sFjVUEjUvMWXA6UI72CZyoeTyQFhQ03n",
        "name": "BW Ocean Green.jpg",
        "width": 482,
        "height": 640
      },
      {
        "fileId": "1P2ojmhf1JALwXM80uT4kJQEi_CnGrUHP",
        "name": "BW Pearl.jpg",
        "width": 1112,
        "height": 945
      },
      {
        "fileId": "1Cv4DGwp73uPGReJSqD3foQae0iKkXtv2",
        "name": "BW Gray Smoke.jpg",
        "width": 1260,
        "height": 945
      },
      {
        "fileId": "1qdbAggRK4m6ULZmaplVF3XySSumS4bHg",
        "name": "BW Jungin Silver.jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "1-ydpF0JHFgYDBzbIEr-Qou5xGHOD2A-C",
        "name": "BW Black River.jpg",
        "width": 640,
        "height": 481
      },
      {
        "fileId": "1138BUu4GcGFtI3X0xyUWOeyNzh2bMKk7",
        "name": "BW Floor Mirror.jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "1aiHEbiUucO0UrUj0xTW9ebgqSbxYcdqF",
        "name": "BW Pearl Double River.jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "10kuxWL66qAyvvjEsGhCyumcFIO8AN-UN",
        "name": "Black Walnut 60x25 Pearl.jpg",
        "width": 1920,
        "height": 812
      },
      {
        "fileId": "18Tbt6ZG-NaLfpTcnHDHB4ZiyzyUK3QZw",
        "name": "Black Walnut 84x40 White Smoke.JPG",
        "width": 1447,
        "height": 1204
      },
      {
        "fileId": "1a792NN1k_nfnOtvnZ2dMTaLBFdPzmHiB",
        "name": "Black Walnut 87x47 Gray Smoke.jpg",
        "width": 1440,
        "height": 1920
      },
      {
        "fileId": "1Bum_b8nhJO2iB9NbGwuURTQISYVXRq-b",
        "name": "Black Walnut 42x31 Oval Pacific Blue 3D.jpg",
        "width": 1920,
        "height": 1440
      },
      {
        "fileId": "18mr9TXiHkf_Z-RnxoJt2SiJi5zJTubRS",
        "name": "Black Walnut 36 Round Marble Resin.jpg",
        "width": 1920,
        "height": 1440
      },
      {
        "fileId": "14DN96FAudHY9sG70SMbvywzdw3KquftC",
        "name": "Black Walnut Solid.png",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1lBtwWSGlUPMElfRm6gTs153WnVe3zvWz",
        "name": "BW Solid.jpg",
        "width": 1440,
        "height": 1920
      },
      {
        "fileId": "1Lm64WnsqfuKVAxY8-O3Fb9sqGzvPy4ZT",
        "name": "Black Walnut 96x46 Blue Artisan Full Pour.jpg",
        "width": 481,
        "height": 640
      },
      {
        "fileId": "1WzxFkO6lkaJvUG_j1DQq9HIlEnoj5VjH",
        "name": "Black Walnut Ocean.jpg",
        "width": 1920,
        "height": 1225
      },
      {
        "fileId": "1DOdBlmQFrNVS3U6xdia75pPWx4MTbte7",
        "name": "BW Cocktail with Pacific Blue 43x24.jpg",
        "width": 960,
        "height": 1280
      },
      {
        "fileId": "1iYmltOT4cbh4Tt7AaAe818dRpkmWqU8j",
        "name": "Black Walnut with Merlot 60.jpg",
        "width": 960,
        "height": 1280
      },
      {
        "fileId": "1aOvRmym4FtkTDWdIaAS9lNY624M42_h9",
        "name": "Black Walnut Dining Table.png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1SrAP_RQmsG38Fu7STgrdDWaWnEwbZ4f3",
        "name": "Black Walnut River Rock Round(1).png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "15HtonIWrqhhNp3tWFmPRHfBhXbJzxjcU",
        "name": "Black Walnut River Rock Round.png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1HwoPN4m6hTjTUTWQAWg1pdrid1_gMBYB",
        "name": "BW Merlot 3D.jpg",
        "width": 814,
        "height": 1280
      },
      {
        "fileId": "1Px0TJybWkJeE659pP1e6UWJhwvQMiaLa",
        "name": "BW CKT Pacific Blue.png",
        "width": 1080,
        "height": 810
      },
      {
        "fileId": "12ArRDG9azlPkPwEH_KbUSj4_ofyBW4ik",
        "name": "Black Walnut 1-slab.png",
        "width": 640,
        "height": 480
      },
      {
        "fileId": "1GG-i9kdPMc7Tt9TOqbDE7LWg25ikV8wW",
        "name": "Black Walnut with Copper (2).png",
        "width": 1227,
        "height": 920
      }
    ],
    "varieties": []
  },
  {
    "name": "Buckeye",
    "slug": "buckeye",
    "coverImage": "/images/wood-species/buckeye-cover.jpg",
    "photoCount": 4,
    "driveFileIds": [
      {
        "fileId": "15FKC1fyAiU4mQfLHGzm_a1sfBBJy8XsA",
        "name": "Buckeye Burl.jpg",
        "width": 481,
        "height": 640
      },
      {
        "fileId": "164WXVlEEmxmZvRyMV0BdKpU6P3d0AE_I",
        "name": "Buckeye Burl Olive Green Corner Table.jpg",
        "width": 481,
        "height": 640
      },
      {
        "fileId": "1vuessAix0ks3vSkh6PgegpjlI_2iwFB9",
        "name": "Buckeye Burl Lagoon Table with Stump.jpg",
        "width": 1260,
        "height": 945
      },
      {
        "fileId": "1WX_jzzZUdCtzbN7TuOSqM7iNlfNo63OZ",
        "name": "Buckeye Lagoon.jpg",
        "width": 1260,
        "height": 945
      }
    ],
    "varieties": []
  },
  {
    "name": "Butternut",
    "slug": "butternut",
    "coverImage": "/images/wood-species/butternut-cover.jpg",
    "photoCount": 3,
    "driveFileIds": [
      {
        "fileId": "1btVYA8uZCOWGeIvjmP2p4vVkKGVxzRb0",
        "name": "Butternut 96x44 Double River Black 3D.jpg",
        "width": 3024,
        "height": 4032
      },
      {
        "fileId": "1wyw5w1hFFK7pR6puMBWtYJXwiQXJ_PAq",
        "name": "Butternut 44x26 Macaw Blue FP.jpg",
        "width": 3024,
        "height": 4032
      },
      {
        "fileId": "1x3vX9h8e3fJiEqF2PdmCGGp_IH7p8yzB",
        "name": "Butternut.HEIC",
        "width": 4032,
        "height": 3024
      }
    ],
    "varieties": []
  },
  {
    "name": "Catalpa",
    "slug": "catalpa",
    "coverImage": "/images/wood-species/catalpa-cover.jpg",
    "photoCount": 2,
    "driveFileIds": [
      {
        "fileId": "1V8PIXhpQIGWR6zKk62myOZqWIiMiDWGZ",
        "name": "Catalpa Oval.JPG",
        "width": 3047,
        "height": 2160
      },
      {
        "fileId": "1mxZjQ73u_5vs-zmb8444sC2UpQGSFHTN",
        "name": "Catalpa Oval Coffee Table.jpg",
        "width": 1471,
        "height": 945
      }
    ],
    "varieties": []
  },
  {
    "name": "Cedar",
    "slug": "cedar",
    "coverImage": "/images/wood-species/cedar-cover.png",
    "photoCount": 8,
    "driveFileIds": [
      {
        "fileId": "1MdEJ4_fo92rn5b2lnd2oXdwlbwPkE8i5",
        "name": "Red Cedar with Angel Blue and shells.png",
        "width": 1130,
        "height": 640
      },
      {
        "fileId": "1dZU0HAgoi8beIfAP3edJ90WGcZlkdhgD",
        "name": "Red Cedar with Clear Smoke.png",
        "width": 696,
        "height": 928
      },
      {
        "fileId": "1iFLadJQkJhalG-VR9GJAHeT-l0x_QSQT",
        "name": "Red Cedar with Midnight Blue.png",
        "width": 612,
        "height": 282
      },
      {
        "fileId": "1YnbpURtHV1HDu-KmGQ0Kco3Oe1rn7sLo",
        "name": "Red Cedar.png",
        "width": 1238,
        "height": 928
      },
      {
        "fileId": "1ndE3PAcPpFOqV6YzHI06_oc57yWXu9ot",
        "name": "Red Cedar and Black Bistro Table.jpeg",
        "width": 686,
        "height": 911
      },
      {
        "fileId": "1_iII5PtuEn-p1IhjV4sptsrLVaMJsJNQ",
        "name": "Red Cedar with Maple Middle.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "17qOYQkMV9bk4h4q4YE2DwNz-Un98dlgL",
        "name": "Cedar with Black 3D.jpg",
        "width": 3921,
        "height": 2737
      },
      {
        "fileId": "1Cy8fRJdv7EkbkyJ5Xgq39grsW3gphslc",
        "name": "Red Cedar 95x40 Farmhouse w Breadboard Ends.jpg",
        "width": 1408,
        "height": 1560
      }
    ],
    "varieties": []
  },
  {
    "name": "Cherry",
    "slug": "cherry",
    "coverImage": "/images/wood-species/cherry-cover.png",
    "photoCount": 16,
    "driveFileIds": [
      {
        "fileId": "1RJbL4PluzNnqzLeW--i6xKnSN4I8riC1",
        "name": "Cherry Burl Cocktail.png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1luG5aArIzQIrCF6N5DZkBHDC8EdFps6m",
        "name": "Cherry and Black Walnut with Samurai Black 3D Double River.jpg",
        "width": 1260,
        "height": 945
      },
      {
        "fileId": "1LVmNxPX_GYHT5qNbbszMtOOdyFDukv9h",
        "name": "Cherry with Copper.png",
        "width": 690,
        "height": 920
      },
      {
        "fileId": "14PcRY0QQoi7S7VXMLjBJp4FMU_5vzIpc",
        "name": "Cherry Waterfall.png",
        "width": 1227,
        "height": 920
      },
      {
        "fileId": "1EYVBuhFTJRgZiyofcF3viDNB8xy-GUon",
        "name": "Cherry with Black 3D.jpeg",
        "width": 686,
        "height": 911
      },
      {
        "fileId": "1368M51YzemR2JsBVuYfqH5pxHjKxP-jn",
        "name": "Cherry Nokia Blue.jpg",
        "width": 3024,
        "height": 4032
      },
      {
        "fileId": "1B22BqzHtUOoOawK2LNJdrjLEgctij4-8",
        "name": "Cherry Oval 96x39 Samurai Black 3D Pour.jpg",
        "width": 640,
        "height": 368
      },
      {
        "fileId": "1saY5DiIqtJ4W8cOxOw1-tarC5FOgcL01",
        "name": "Cherry.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1574A1xAkf-K8XnAkW4hfyeI9rEsupsXx",
        "name": "Cherry w- bench.webp",
        "width": 1238,
        "height": 928
      },
      {
        "fileId": "1ZuF5jsT5aCV0PmduaFvV04-kYMQI7Mzl",
        "name": "Cherry w- copper.jpg",
        "width": 569,
        "height": 640
      },
      {
        "fileId": "1kiyDnsZFoP8YT9B6JGSrFytgvRRmkG4e",
        "name": "Boards Image(163).png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "19cMFrI8k-oL2w3aUFlCPiPAAAtvji5J7",
        "name": "Cherry.png",
        "width": 1227,
        "height": 920
      },
      {
        "fileId": "1v0YuIu2DPkpUU6IlGM3XBI37emQ8P9Mi",
        "name": "36” Cherry Artisan on Center Prong.png",
        "width": 768,
        "height": 1024
      },
      {
        "fileId": "13nCkGqwTtw4mnyVVt7SNeCJnYwOOOQuE",
        "name": "40” Round Cherry Burl with Teal.png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1Y007MCuKCPX7lwXPO3AcodtQ2sjWOX_K",
        "name": "Cherry w Copper.png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1RdRlniR6bCUi7Hj-d0b_IczYi5zycFcH",
        "name": "Cherry.JPG",
        "width": 4032,
        "height": 3024
      }
    ],
    "varieties": []
  },
  {
    "name": "Chestnut",
    "slug": "chestnut",
    "coverImage": "/images/wood-species/chestnut-cover.jpg",
    "photoCount": 3,
    "driveFileIds": [
      {
        "fileId": "1QbN2zaaRmFZVbx2yTPezup_IyxHi_Yzy",
        "name": "Chestnut with Midnight Blue Full Pour.jpg",
        "width": 470,
        "height": 347
      },
      {
        "fileId": "1mbLCLjpH2_2vmOBZmmxRMxLUIpA6rJCj",
        "name": "Chestnut with Pacific Blue Rivers.jpg",
        "width": 1260,
        "height": 945
      },
      {
        "fileId": "1CVLbhgQQIH64RdWzKMv34ymJkwbA7OKg",
        "name": "Chestnut 42x28 with Black 3D.jpg",
        "width": 1920,
        "height": 1440
      }
    ],
    "varieties": []
  },
  {
    "name": "Claro Walnut",
    "slug": "claro-walnut",
    "coverImage": "/images/wood-species/claro-walnut-cover.jpg",
    "photoCount": 4,
    "driveFileIds": [
      {
        "fileId": "1TOWn0cjzm1d2Cy1w2j_e-aB3ZJdA35dZ",
        "name": "Claro Burls.jpg",
        "width": 1260,
        "height": 945
      },
      {
        "fileId": "13NtggDSecuJ1wQQ8XJXyO4pmpxRksY6E",
        "name": "Claro Walnut Cookies and resin.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1RR-vWEbhlSzLRJedCJoXVuq6T-QJ3Q5I",
        "name": "Claro Walnut Cookie 36 diam red accent.jpg",
        "width": 1920,
        "height": 1440
      },
      {
        "fileId": "16zSqNBzqnnLiK7AdnZn-fPipIOA2p3UG",
        "name": "Soliod Claro Walnut 2.jpg",
        "width": 1178,
        "height": 1298
      }
    ],
    "varieties": []
  },
  {
    "name": "Cotton Wood",
    "slug": "cotton-wood",
    "coverImage": "/images/wood-species/cotton-wood-cover.jpg",
    "photoCount": 5,
    "driveFileIds": [
      {
        "fileId": "14mDBWUUNFYVJWFIl4ZZ92OmKK_08gDC_",
        "name": "Cottonwood Lace Burl Slab.jpg",
        "width": 1440,
        "height": 1920
      },
      {
        "fileId": "171qsmuXxuQaWFM4K27uWqBPCI80q29Sr",
        "name": "Cottonwood Cocktail Table(1).png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1SAJVgKweoOz1vv3FXKF_wtC0v0kXUkoi",
        "name": "Cottonwood Cocktail Table (2).png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1FcljMqzEpQ-vp5vrxcHLSDPTcJLf_UQ3",
        "name": "Cottonwood Cocktail Table .png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1j0qu5lX__A3F5PM3gDI4YxFOXW8h5f3Y",
        "name": "Cottonwood Cocktail Table (1).png",
        "width": 2016,
        "height": 1512
      }
    ],
    "varieties": []
  },
  {
    "name": "Douglas Fir",
    "slug": "douglas-fir",
    "coverImage": "/images/wood-species/douglas-fir-cover.png",
    "photoCount": 6,
    "driveFileIds": [
      {
        "fileId": "1kj6BuZtKJ2UprwYa7Lei0RK_HTgiHU-A",
        "name": "6’ Douglas Fir Dining Table(4).png",
        "width": 1512,
        "height": 2016
      }
    ],
    "varieties": [
      {
        "name": "Douglas Fir",
        "slug": "douglas-fir",
        "coverImage": "/images/wood-species/douglas-fir-cover.png",
        "photoCount": 5,
        "driveFileIds": [
          {
            "fileId": "1eBwWq2oZI_Uai_U0-1pX27SiH2xqwtgK",
            "name": "6’ Douglas Fir Dining Table(3).png",
            "width": 2016,
            "height": 1512
          },
          {
            "fileId": "1nQLGc7XgxyltAQNKgGxMfRw2RT9Ihkzq",
            "name": "6’ Douglas Fir Dining Table(4).png",
            "width": 1512,
            "height": 2016
          },
          {
            "fileId": "1Wc6W--Xogs5LwOOW6eJQvWmYEaen4aIU",
            "name": "6’ Douglas Fir Dining Table(2).png",
            "width": 2016,
            "height": 1512
          },
          {
            "fileId": "1pOLljFXIYw1UWqveOdSguCGIEULX0czl",
            "name": "6’ Douglas Fir Dining Table(1).png",
            "width": 2016,
            "height": 1512
          },
          {
            "fileId": "1Wi4K2Qhs-gKcJ1El5EHAanhgGa-8n6bt",
            "name": "6’ Douglas Fir Dining Table.png",
            "width": 2016,
            "height": 1512
          }
        ],
        "varieties": []
      }
    ]
  },
  {
    "name": "Elm",
    "slug": "elm",
    "coverImage": "/images/wood-species/elm-cover.jpg",
    "photoCount": 10,
    "driveFileIds": [
      {
        "fileId": "1Vfeh15sNGOo1GS4MmGIzAjNuMFy0l-XP",
        "name": "Elm with Black.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1Xl-CxQl592l2_M553oiXW_PDlxUwTkIU",
        "name": "Elm & Mahogany 72x36 McCaw 3D.jpg",
        "width": 1260,
        "height": 945
      },
      {
        "fileId": "16VtEJIQ60g1-X45zXc4Xp6TiAoGBSek_",
        "name": "Elm SS Black FP.jpg",
        "width": 640,
        "height": 567
      },
      {
        "fileId": "1oENfilXqsS5PUQrAeB6vWKdHbunwn8w4",
        "name": "Elm Solid.png",
        "width": 1303,
        "height": 751
      }
    ],
    "varieties": [
      {
        "name": "English Elm",
        "slug": "english-elm",
        "coverImage": "/images/wood-species/english-elm-cover.jpg",
        "photoCount": 2,
        "driveFileIds": [
          {
            "fileId": "1nTcF6G1HeQfxkpR1FWvf8hE_vw9F0kjj",
            "name": "English Elm 80x43 Midnight Blue.jpg",
            "width": 1260,
            "height": 945
          },
          {
            "fileId": "1__en6R5t71SWCRDTLFSobpwSGIExY25F",
            "name": "Oiled English Elm RR Pacific Blue 88x41.jpg",
            "width": 960,
            "height": 1280
          }
        ],
        "varieties": []
      },
      {
        "name": "Spalted Elm",
        "slug": "spalted-elm",
        "coverImage": "/images/wood-species/spalted-elm-cover.png",
        "photoCount": 2,
        "driveFileIds": [
          {
            "fileId": "1xLI4lGDP3ZnogE8n9KYYGXTiTJWxKdek",
            "name": "6’ Spalted Elm Maple Copper Resin Round.png",
            "width": 1512,
            "height": 2016
          },
          {
            "fileId": "1fIONb778DGIFdDTMzUd7SEreAFeEPIcb",
            "name": "Spalted Elm Bench.png",
            "width": 2016,
            "height": 1512
          }
        ],
        "varieties": []
      },
      {
        "name": "White Elm",
        "slug": "white-elm",
        "coverImage": "/images/wood-species/white-elm-cover.png",
        "photoCount": 2,
        "driveFileIds": [
          {
            "fileId": "1ftLIQxrVtEzSUfROxxhV3-hQPkjtFwL9",
            "name": "White Elm Dining Table(2).png",
            "width": 1512,
            "height": 2016
          },
          {
            "fileId": "1i9q6Vsw1i2YF1aApUwt-tq2fnlcpEHqb",
            "name": "White Elm Dining Table.png",
            "width": 2016,
            "height": 1512
          }
        ],
        "varieties": []
      }
    ]
  },
  {
    "name": "English Walnut",
    "slug": "english-walnut",
    "coverImage": "/images/wood-species/english-walnut-cover.jpg",
    "photoCount": 19,
    "driveFileIds": [
      {
        "fileId": "1R-6_O-XNexf8KRZFShy9sbZSu-_SwSmn",
        "name": "English Walnut with Emerald Green 3D.jpg",
        "width": 507,
        "height": 580
      },
      {
        "fileId": "1BXeXh80X_A58e0XbRGLZ1_CEtBsJQuT0",
        "name": "English Walnut Double Cookie with Angel Blue fill.jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "18dSBcReBdzNY_hSZhWbDouQPwVxQvKIc",
        "name": "English Walnut with Maple Island Deep Ocean Green 3D.jpg",
        "width": 1260,
        "height": 945
      },
      {
        "fileId": "16ypYbr6kMgbAwETQxHbD0hbOs-0gbVRQ",
        "name": "English Walnut with Black.jpg",
        "width": 716,
        "height": 911
      },
      {
        "fileId": "1plfcFB4ySeJA83DCP59lnvb8RTS_uhHG",
        "name": "English Walnut RR  .jpg",
        "width": 3024,
        "height": 3390
      },
      {
        "fileId": "1dycqlK5y4kASckhzruMh_JjN95WZMNaM",
        "name": "English Walnut Midnight Blue & Gold Lift Desk.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1NKXSO-iy3dqZyJsVBPm3a_eZy0rCliU7",
        "name": "EW Angel Blue.jpg",
        "width": 1115,
        "height": 714
      },
      {
        "fileId": "1etxVuUDYd1MEHaOj1UY6EXS7LN9ScYhn",
        "name": "IMG_5718.jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "15LfgALOvnPVoHJBxdreZpZHhpR1Dga-K",
        "name": "English Walnut Deep Ocean Green (2).jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "1oA4xlmfgqD-Kl4UjtLoOBd3GWjmdCiYw",
        "name": "English Walnut 60x36 Black FP (1).HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "18HbcAOsrOy3CK7qQq0TkYkWSjX5CZIc4",
        "name": "English Walnut Cookie 56x52 Macaw FP.jpg",
        "width": 1920,
        "height": 1440
      },
      {
        "fileId": "1VkDApPb5psce9kXAwRIKlrpghRs6WKwX",
        "name": "English Walnut 41x26 Double Cookie Baku Red.jpg",
        "width": 1451,
        "height": 1243
      },
      {
        "fileId": "1SGvsw3pK_Xuo5GoDITzT-QjgkXyy8Zpa",
        "name": "English Walnut 41x26 Double Cookie Nokia Blue.jpg",
        "width": 1920,
        "height": 1440
      },
      {
        "fileId": "1U3en1J_hoC3fZg3wbS0LiU9KS4ukGbIr",
        "name": "English Walnut - River Rocks Pacific Blue.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1zG7OLCAZq_lW6VGXSr9fYyo1ke779waY",
        "name": "English Walnut -Deep Ocean Green.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1Zlk7dYqh4wbSk_6Z196tHpu2Irk-0Fcr",
        "name": "Eng Walnut DK Ocean Green.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "11V5Fml6Z2dUeMA0ffxIaXy8e2K7rvvJq",
        "name": "English Walnut Copper.webp",
        "width": 600,
        "height": 800
      },
      {
        "fileId": "1iD2K9X5SecCtxr-VOvM8Rm-rFvPtrI9Y",
        "name": "English walnut with Pacific Blue River and Voltage.png",
        "width": 3976,
        "height": 3009
      },
      {
        "fileId": "1oP1MvBV3wUWue0jdGHFeaFuRtFVhkGpr",
        "name": "English Walnut RR.heic",
        "width": 4032,
        "height": 3024
      }
    ],
    "varieties": []
  },
  {
    "name": "Figured Maple",
    "slug": "figured-maple",
    "coverImage": "/images/wood-species/figured-maple-cover.jpg",
    "photoCount": 19,
    "driveFileIds": [
      {
        "fileId": "1PKyezdk1SHQ_KgsbOd1w9tC0m8p8l6sD",
        "name": "Figured Maple Live Edge Bar Tops.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1tQj5DhFA8-zqqDgfAOZwYFLILNwd4uMZ",
        "name": "Figured Maple RR.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1MhS2HBB_79qdZW0jB7Y2QgDk6bkIOeA7",
        "name": "Figured Walnut with Curva Base.jpeg",
        "width": 686,
        "height": 911
      },
      {
        "fileId": "10nkvMiSqp_grjidmRhjmRBVWHBXlmb-I",
        "name": "Fig Maple Red Black 2.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1PJCn2W6cJc81mv3QuI6qLlR5Y1-PG-Fv",
        "name": "Figured Maple.jpg",
        "width": 799,
        "height": 911
      },
      {
        "fileId": "1kkPLnS8bITZDkFeYaoo6TAOH9-IQSdPc",
        "name": "Figured Maple (2).jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1W-0vwwiekv0jKV8cqmk9PNgX3qNult98",
        "name": "Figured Maple Red Black.jpg",
        "width": 481,
        "height": 640
      },
      {
        "fileId": "1EJZjsiRl2YTw8LRLbkVYAysUqHjDMR32",
        "name": "Figured Maple Duo Blue Green.jpg",
        "width": 3024,
        "height": 4032
      },
      {
        "fileId": "18G2POraorpvq1Oi-mfrXz4d0g37G3A4h",
        "name": "FM Pearl RR.jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "15fBgt_y-jNzx8KObyY-aGjVnoIWyLIUO",
        "name": "Fig Maple Nokia Blue.jpg",
        "width": 696,
        "height": 928
      },
      {
        "fileId": "1xluIWGTVMZtTN2eUO3giHS7KJcyXojVZ",
        "name": "Figured Maple Ocean.jpg",
        "width": 481,
        "height": 640
      },
      {
        "fileId": "1s0U-p0i0zYuVu7fFcSTUCe7B737abVp9",
        "name": "Figured Ambrosia Maple 90x42 with Vibrant Red Black.jpg",
        "width": 1440,
        "height": 1920
      },
      {
        "fileId": "1rx3PEPCD_CogP_07QjXZKNP0XNC6M8Om",
        "name": "figured maple cookie merlot.jpg",
        "width": 1920,
        "height": 1440
      },
      {
        "fileId": "1k89g1PB1pcD4O0LBpdh6-1IEqZPSQuea",
        "name": "Figured Maple with Merlot 62x36.jpg",
        "width": 960,
        "height": 1280
      },
      {
        "fileId": "1lWgQaUShnGhXtMIZhYonoyrusmmTmN-a",
        "name": "Figured Maple.png",
        "width": 690,
        "height": 920
      },
      {
        "fileId": "1I2q0udHBuKyvIPVpxP1ouL1HYjCg-eZl",
        "name": "Fig Maple Red Black.png",
        "width": 690,
        "height": 920
      },
      {
        "fileId": "1ASPHbks_h1-r0U6JFFKemANmdf6hcv3n",
        "name": "FM Black.png",
        "width": 1227,
        "height": 920
      },
      {
        "fileId": "12FMY8CHgnHibM0_DTHSxD22WujYX0lDF",
        "name": "Figured Maple Pacific Blue.png",
        "width": 1303,
        "height": 977
      },
      {
        "fileId": "1tBUSm1l6J2G_Zo9PC5LUXIMDugbbpy7M",
        "name": "Figured Maple w Black.png",
        "width": 1227,
        "height": 920
      }
    ],
    "varieties": []
  },
  {
    "name": "Flaming Box Elder",
    "slug": "flaming-box-elder",
    "coverImage": "/images/wood-species/flaming-box-elder-cover.jpg",
    "photoCount": 17,
    "driveFileIds": [
      {
        "fileId": "1J91LU53VOaaYa_PSaCFb1oUfxLjdeRjP",
        "name": "FBE Dark Ocean BLue 3D.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1wVZ8JhSG76VgY2xI4j7oVDnmPAYWcdph",
        "name": "FBE Macaw Blue Green 3D.jpg",
        "width": 1260,
        "height": 945
      },
      {
        "fileId": "1kXbKouIiRS_QaQ4iTm2OdvqYy0oCRyZ1",
        "name": "FBE Solid.jpg",
        "width": 482,
        "height": 640
      },
      {
        "fileId": "1UoCVO_5nx-yQZmJ8p9HsZ-No69b0SKLN",
        "name": "FBE Angel Blue 3D with Voltage.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1kWOoQorfJ1ooqelH2diChACFZG67YeYT",
        "name": "FBE Angel Blue 3D fill.jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "1TAp26sk1nXT-aKhFyRpQ403ijunj4W6T",
        "name": "FBE with Angel Blue 3D.jpg",
        "width": 3024,
        "height": 4032
      },
      {
        "fileId": "1SMJedM9DN3BBjWlnnltOQVeN2vyIqe48",
        "name": "FBE Pacific Blue.jpg",
        "width": 3024,
        "height": 3284
      },
      {
        "fileId": "1-SKo1ytS6F8egVMo-ugf-kJGJOTI3QSL",
        "name": "FBE Slab.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1rfvUQ1qAPmVtIZiv9lR9b56lAPqxJtE0",
        "name": "FBE Crotch.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1Aut1hmPQNTgG8FqlBzCYEpNykk3lS2XY",
        "name": "IMG_9364.jpg",
        "width": 3024,
        "height": 4032
      },
      {
        "fileId": "1tNrGEY6iOYks0DUaaRZSncxptSOwSvtg",
        "name": "Flaming Box Elder Solid.jpg",
        "width": 1260,
        "height": 945
      },
      {
        "fileId": "195gpMgVK1RjkRp_RNBBTS9MI8PlEZS9j",
        "name": "67398102814__AE4F515F-E5EB-45A9-824F-86863233EFA3.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1Swxpb_T9tyL4D1R_g9qbA3znb5uT-arc",
        "name": "8’ Flaming Box Elder River Dining w-Voltage(1).png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1p_amjIOPG5jTqsAkiCFlIdaRqQQ1KM9u",
        "name": "Oval Flaming Box Elder(1).png",
        "width": 1512,
        "height": 2016
      },
      {
        "fileId": "16gW3aOK6xzMrH0W-vXj-jHe3nQWqH6af",
        "name": "8’ River Rock Flaming Box Elder(1).png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1PPeI-i53xYiuMZ58a-et_htYDx_GZWeQ",
        "name": "Box Elder with River Rock.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1ngo3D0gotHodAYXJGGq8CrCmpd4hcZmZ",
        "name": "Flaming Box Elder Pacific Blue.HEIC",
        "width": 4032,
        "height": 3024
      }
    ],
    "varieties": []
  },
  {
    "name": "Gunacoste",
    "slug": "gunacoste",
    "coverImage": "/images/wood-species/gunacoste-cover.jpg",
    "photoCount": 7,
    "driveFileIds": [
      {
        "fileId": "1ad695ynR19ZO3E7HLvFlerB_jsW1zVWO",
        "name": "Gunacoste RR.jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "1vNdzI9WBACFN9A4b1sPouWV6DahyXqby",
        "name": "Gunacoste Double Tree.jpg",
        "width": 1260,
        "height": 945
      },
      {
        "fileId": "1XCkbVW8e7TarRiW0YCHOKuVI2BkDRkEx",
        "name": "Gunacoste with Carolina Blue.png",
        "width": 1238,
        "height": 928
      },
      {
        "fileId": "1Af_wbEB6mLk_rqre922rr5UkIL2dcQvG",
        "name": "Gunacoste (Acadia) Dining Table.png",
        "width": 1512,
        "height": 2016
      },
      {
        "fileId": "10g5t5URUQU245Hq-sNjbeC8BJOMXDw0a",
        "name": "Gunacoste Dining Table(3).png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1sLpRN4CJgcw_YZKpEmhy4M6WB4UzUH54",
        "name": "6’ Gunacoste Dining Table(2).png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "15zUjblf8Ygv3OxnqhEH7sYIeyYMA7Xkf",
        "name": "Gunacoste Dining Table(2).png",
        "width": 2016,
        "height": 1512
      }
    ],
    "varieties": []
  },
  {
    "name": "Hemlock",
    "slug": "hemlock",
    "coverImage": "/images/wood-species/hemlock-cover.jpg",
    "photoCount": 1,
    "driveFileIds": [
      {
        "fileId": "1VBe0Tpdl8D0cU1-2KOSmau6F2bnk8V_v",
        "name": "IMG_0873.jpg",
        "width": 683,
        "height": 911
      }
    ],
    "varieties": []
  },
  {
    "name": "Hickory",
    "slug": "hickory",
    "coverImage": "/images/wood-species/hickory-cover.jpg",
    "photoCount": 19,
    "driveFileIds": [
      {
        "fileId": "1tGKjJsry5YLl_a1qMVc3Uw247fBa1Jt8",
        "name": "Hickory 84x42 Solid.jpg",
        "width": 1440,
        "height": 1920
      },
      {
        "fileId": "1QyOKPqoywGWcAoWJ9OoLaQXnOQmeNBjq",
        "name": "Hickory Round.jpg",
        "width": 1215,
        "height": 911
      },
      {
        "fileId": "1yacjjrh74evkQBF2QplKQOmvsh5TxkBk",
        "name": "Hickory 72x42 Black Full Pour LE.jpg",
        "width": 1920,
        "height": 2560
      },
      {
        "fileId": "15MYakaeHN9ITUP7j6oavQFuN8pZox5qD",
        "name": "Hickory Dbl RR.jpg",
        "width": 1260,
        "height": 945
      },
      {
        "fileId": "134BqepaT7jXiYsHtA3Y5GMEySuPhv44t",
        "name": "Hickory Round.jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "1KFzNjU5rfFvkfmQ7vaBCCNHfzgsR7f83",
        "name": "Hickory and BW with Beetle Blue.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1UsMTbVOgHgzPt2WeZp8gfFCTBTTODqMp",
        "name": "Hickory Pacific Blue.png",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1IbBPf6dVl8Qc7kH-Ot1QGH-I2t6TNYdx",
        "name": "Hickory Round RR.png",
        "width": 2736,
        "height": 2577
      },
      {
        "fileId": "1sYfpzqPqqS0IPK1mls5r8WwyYR8vhkfz",
        "name": "Hickory Dbl River.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "18AbT5Paa3a9flH28G1EhHbpeAFE529d2",
        "name": "Hickory Copper FP.jpg",
        "width": 481,
        "height": 640
      },
      {
        "fileId": "1J54bI-RA0r8HoqZwTLno-y4SVJwNDPUC",
        "name": "Hickory & Mahogany.jpg",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1j1OBYjmHqYIBBTJiZd1eF6TFLi5wmSMO",
        "name": "Hickory with Black FP.jpg",
        "width": 3024,
        "height": 4032
      },
      {
        "fileId": "1XdH9NT0DBP27MZ_Dzf4eQ5Fwy8yZZTPa",
        "name": "hickory solid.jpg",
        "width": 480,
        "height": 640
      },
      {
        "fileId": "1AKwbuTdMpuA7OFhFCtQJLf4HyNXd7vTA",
        "name": "HICK Pacific Blue.jpg",
        "width": 2499,
        "height": 3557
      },
      {
        "fileId": "16ivpU3H0iqLYyeBgxizOF2h3Px6kMimE",
        "name": "Hickory 52x32 Cocktail Walnut Insert Samurai Black 3D.jpg",
        "width": 1920,
        "height": 1091
      },
      {
        "fileId": "15zdvzs_zrsYOVHkAxQ8RPBIWX1zz0hGv",
        "name": "Hickory 48x28 Blue Smoke.jpg",
        "width": 1920,
        "height": 1440
      },
      {
        "fileId": "1YNTHys1FZrOFMl95pjKlZxoOnIhvGSNk",
        "name": "Hickory and Walnut River Rock.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1Lo1lg66xswbT72ecUPx6QD7IkaqDr-H-",
        "name": "Hickory LE.png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1qCTfDodBpnk23dWdJIVnRhY-clBoSh3A",
        "name": "Hickory.JPG",
        "width": 4032,
        "height": 3024
      }
    ],
    "varieties": []
  },
  {
    "name": "Mahogany",
    "slug": "mahogany",
    "coverImage": "/images/wood-species/mahogany-cover.jpg",
    "photoCount": 1,
    "driveFileIds": [
      {
        "fileId": "1f260fSuywEmyKVqgqshXDaxSISYr8kPd",
        "name": "Honduras Mahogany.jpg",
        "width": 683,
        "height": 911
      }
    ],
    "varieties": []
  },
  {
    "name": "Maple",
    "slug": "maple",
    "coverImage": "/images/wood-species/maple-cover.jpg",
    "photoCount": 70,
    "driveFileIds": [
      {
        "fileId": "1b1e06TeyKV7K2heIlxsTkoiQRLUw13ww",
        "name": "Maple and Beetle Blue.jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "1BEggsFOW79q9MUmsP6dtgJIDRD-BDB0R",
        "name": "Maple accent with bowties.jpg",
        "width": 1221,
        "height": 945
      },
      {
        "fileId": "18I7RgTJsQhJwGf2R0hfmOFKciIH0jLlV",
        "name": "Maple with Ocean river.jpg",
        "width": 1215,
        "height": 911
      },
      {
        "fileId": "1EllQAeRhjhfTxHR7F1ylZyt4CROnhfA5",
        "name": "Maple live edge coffee table.jpeg",
        "width": 686,
        "height": 911
      },
      {
        "fileId": "10VIdkttW0riPFq-Ebe5jb-ATf8mCfNeU",
        "name": "Maple on center interlock.jpeg",
        "width": 686,
        "height": 911
      },
      {
        "fileId": "1sMYN2SR81tZQu3MdZRy-67zcK3z0uZld",
        "name": "Tiger Maple.jpg",
        "width": 480,
        "height": 640
      },
      {
        "fileId": "15adyl2qwmm3uGDftPfd3g1F0qveOkuQC",
        "name": "Maple solid with Benches.jpg",
        "width": 640,
        "height": 480
      },
      {
        "fileId": "1Lo-KKNOqRMC4-JQ_4RgGstJuz0lBqrck",
        "name": "Maple Crotch- Macaw Blue Green.jpg",
        "width": 1920,
        "height": 1440
      },
      {
        "fileId": "1P-SJibnL2aw15ItFxh4BuiX85uJY1Q7s",
        "name": "Maple with Angel Blue 3D.jpg",
        "width": 1215,
        "height": 911
      },
      {
        "fileId": "1LLGFEk5ZUh-V6ga8UAxtGWJKBaeeIOxb",
        "name": "Maple with Angel Blue deep 3D.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1rz1-i7uDxRfdPs5_nCy02zlUyv9B9F9K",
        "name": "Maple and Pacific Blue 3D Rivers.jpeg",
        "width": 686,
        "height": 911
      },
      {
        "fileId": "1BcN6O3IkHg_taoAtSG77qKhKCzwCxsiR",
        "name": "Maple.jpg",
        "width": 828,
        "height": 632
      },
      {
        "fileId": "1c6pVWaoUIlS3TtdKLmpU2sZcsAX2yiM0",
        "name": "Tiger maple .jpg",
        "width": 1013,
        "height": 945
      },
      {
        "fileId": "1KvNaIUVMetZzAsbqT1PXt-bFk5vwXxMi",
        "name": "Maple Picnic.jpg",
        "width": 1260,
        "height": 945
      },
      {
        "fileId": "1CPjqpmVbwxfenE5wqkdiuR47rdF18ktP",
        "name": "Maple Live Edge.jpg",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1kMCyZzK9nH6qvrSC5MzsbzartWUjiI32",
        "name": "Maple Game Table 40 Blue Marble Chessboard Faras Legs.jpg",
        "width": 1920,
        "height": 1440
      }
    ],
    "varieties": [
      {
        "name": "Ambrosia Maple",
        "slug": "ambrosia-maple",
        "coverImage": "/images/wood-species/ambrosia-maple-cover.jpg",
        "photoCount": 6,
        "driveFileIds": [
          {
            "fileId": "1rSweFqBaGK-ArwBEGdrOSRLgZfHHMD-i",
            "name": "Curly Ambrosia.jpg",
            "width": 709,
            "height": 945
          },
          {
            "fileId": "10mRJmYPD_jEOououu0KfFWRO61L6bCZ0",
            "name": "Ambrosia Maple RR.png",
            "width": 2016,
            "height": 1512
          },
          {
            "fileId": "19reaguHdHlqUI_2j1Cc4uUMyGq4vYQ0W",
            "name": "Ambrosia Maple.png",
            "width": 1238,
            "height": 928
          },
          {
            "fileId": "1MmuHxtTFuxfoLJQUUX6wPTDS3ZbYibvT",
            "name": "Ambrosia Maple 84x40.jpg",
            "width": 3024,
            "height": 4032
          },
          {
            "fileId": "18EACs8B_fetV8cgHzzlKuMZQXeOtsCMp",
            "name": "Ambrosia Maple RR.HEIC",
            "width": 4032,
            "height": 3024
          },
          {
            "fileId": "1srSqPFVd8p5pOuKeTNUDwp72yRp1j476",
            "name": "AM8024RR Bar Top (1).jpg",
            "width": 118,
            "height": 320
          }
        ],
        "varieties": []
      },
      {
        "name": "Birdseye Maple",
        "slug": "birdseye-maple",
        "coverImage": "/images/wood-species/birdseye-maple-cover.jpg",
        "photoCount": 4,
        "driveFileIds": [
          {
            "fileId": "1DsZBLQBovJcVPnPsKj6Sykm-5d-v1su9",
            "name": "BE Maple.jpg",
            "width": 2000,
            "height": 1325
          },
          {
            "fileId": "18ZmBCAjXBftOvx-uv5NomQsCrL0vKtI_",
            "name": "Birdseye Maple 46x19 Mink 3D.jpg",
            "width": 3024,
            "height": 4032
          },
          {
            "fileId": "1REARXhTU_db5NnKSrv_4kZIuFTffjnMn",
            "name": "BEM Pacific Blue 3D.jpg",
            "width": 1280,
            "height": 960
          },
          {
            "fileId": "1udYXHvLrs6muoBiffPlPtDAbnHL8XBza",
            "name": "BEM Merlot 3D.jpg",
            "width": 1280,
            "height": 814
          }
        ],
        "varieties": []
      },
      {
        "name": "Figured Maple",
        "slug": "figured-maple",
        "coverImage": "/images/wood-species/figured-maple-cover.jpg",
        "photoCount": 19,
        "driveFileIds": [
          {
            "fileId": "1eXf8K4UxB7SqyXaKxBuuYeZgjyc11kxk",
            "name": "Figured Maple Ocean.jpg",
            "width": 683,
            "height": 911
          },
          {
            "fileId": "1RfyrXQvJNd3JByd4iNZ-NnBb4B5SA4nL",
            "name": "Figured Maple RR 3D.jpg",
            "width": 683,
            "height": 911
          },
          {
            "fileId": "1T9XiISMLM8r0v_pkoko9Yc6hMUwDaGMq",
            "name": "Figured Maple Cookie with Jungin Silver 3D.jpg",
            "width": 481,
            "height": 640
          },
          {
            "fileId": "1BUzR4tD_6x3_6ykdGIw-ox8dLkYRgQIA",
            "name": "Figured Maple Red Black.jpg",
            "width": 481,
            "height": 640
          },
          {
            "fileId": "1BJZ3U23AaHJ84S-hyw8J5iKu3pgaCYki",
            "name": "FM Pearl RR.jpg",
            "width": 709,
            "height": 945
          },
          {
            "fileId": "191K2gEzvB1pKO8eA3eZBI_-Rz3s0OvBo",
            "name": "FM RR over Pacific Blue.jpg",
            "width": 1112,
            "height": 945
          },
          {
            "fileId": "1uBC_rfPa-bZL-f_mBqBebXjAVgUrKick",
            "name": "Fig Maple Nokia Blue.jpg",
            "width": 696,
            "height": 928
          },
          {
            "fileId": "1itYv_x3T5JXQAOBQNoZ0jbfNot_f1AQ3",
            "name": "FM Headboard RR.jpg",
            "width": 709,
            "height": 945
          },
          {
            "fileId": "1-vmLg1SZGxwBvuC2NV11bAVDR-SemwwO",
            "name": "Figured Maple Ocean.jpg",
            "width": 481,
            "height": 640
          },
          {
            "fileId": "1cDjJKPX-byqjeCu2FlY544ZfN6TNfat5",
            "name": "Figured Maple Cookie 30 diam..jpg",
            "width": 1920,
            "height": 1440
          },
          {
            "fileId": "1r__md0oc56_GM4WK9JMLFbpLrxq3sJhd",
            "name": "Figured Maple 60x30 Desk  Ocean Curva Legs.jpg",
            "width": 1440,
            "height": 1920
          },
          {
            "fileId": "1N6hQEEs-pTuWfyfPkj-2L0qV_Een_voY",
            "name": "Figured Ambrosia Maple 90x42 with Vibrant Red Black.jpg",
            "width": 1440,
            "height": 1920
          },
          {
            "fileId": "1wltKrLSQW9Z4V5NkrL0H3aPOd6v85ySA",
            "name": "figured maple cookie merlot.jpg",
            "width": 1920,
            "height": 1440
          },
          {
            "fileId": "1_qmQCryYIiKK-QN72tSZo3BkHoQ3CMXF",
            "name": "Figured Maple with Merlot 62x36.jpg",
            "width": 960,
            "height": 1280
          },
          {
            "fileId": "1k0w8uIM1RCWpN7jSZvpQ5aE1fa1WKrrz",
            "name": "Figured Maple.png",
            "width": 690,
            "height": 920
          },
          {
            "fileId": "16TTBxrBAvIygk0Pbu2iXY5cL2py2EKpm",
            "name": "Fig Maple Red Black.png",
            "width": 690,
            "height": 920
          },
          {
            "fileId": "1VELbqGsWwYjtqCq9AuIeB25uPcCRACLu",
            "name": "FM Black.png",
            "width": 1227,
            "height": 920
          },
          {
            "fileId": "1NYvOYGG5S5fjib4Z8NDeHVeOENOIG4sW",
            "name": "FM Pacific Blue.png",
            "width": 1303,
            "height": 977
          },
          {
            "fileId": "1eso46tv70jWjsqCGuO7Rbb-q6kau9tH3",
            "name": "Figured Maple w Black.png",
            "width": 1227,
            "height": 920
          }
        ],
        "varieties": []
      },
      {
        "name": "Hard Maple",
        "slug": "hard-maple",
        "coverImage": "/images/wood-species/hard-maple-cover.jpg",
        "photoCount": 9,
        "driveFileIds": [
          {
            "fileId": "1rhJrXMIu_G94Mvx6IsaNeZHYG0KA-P8P",
            "name": "Maple with Carolina Blue.JPG",
            "width": 709,
            "height": 945
          },
          {
            "fileId": "19qWLZz8kS_yePHRBdZKa7Zn4PxHN3nQY",
            "name": "Curly Ambrosia Farmhouse with Breadboards.jpg",
            "width": 683,
            "height": 911
          },
          {
            "fileId": "1tiv4Q8_1IhNlv4NxWKFM47Rbd8_R0ni3",
            "name": "Hard Maple.jpg",
            "width": 1260,
            "height": 945
          },
          {
            "fileId": "1rM9HP6fRQblb9SkEyjTKfcoJTdQFUq8Y",
            "name": "Hard Maple with Black FP.jpg",
            "width": 481,
            "height": 640
          },
          {
            "fileId": "1y2C2YW_xLsuFlzLql4IuDL1Q04pQsxAu",
            "name": "Hard Maple 58x30  White Smoke.jpg",
            "width": 1920,
            "height": 1440
          },
          {
            "fileId": "1jzMszMxTFapvt47RRdoFvp8KZu0PV8Cx",
            "name": "67847218087__DDBB8E13-0CE3-4814-BD8F-FD2B4128AB14.HEIC",
            "width": 4032,
            "height": 3024
          },
          {
            "fileId": "1mWrDezB4U0OqLQdilNbd7QgKgFNSnpEj",
            "name": "40” Hard Maple Blue River Round(2).png",
            "width": 2016,
            "height": 1512
          },
          {
            "fileId": "1Xy9f6ZPMlmxwujlouUPAZgGebaT1cD6E",
            "name": "40” Hard Maple Blue River Round(1).png",
            "width": 2016,
            "height": 1512
          },
          {
            "fileId": "11Cc0tlw31nnSOiwylNLYIQ_IdYYB1CMK",
            "name": "40” Hard Maple Blue River Round.png",
            "width": 2016,
            "height": 1512
          }
        ],
        "varieties": []
      },
      {
        "name": "Maple Burl",
        "slug": "maple-burl",
        "coverImage": "/images/wood-species/maple-burl-cover.jpg",
        "photoCount": 4,
        "driveFileIds": [
          {
            "fileId": "1Iomhc17joPpfIr9GHOMStTzT96i5U64_",
            "name": "Maple Burl Cookie on Lithe.jpg",
            "width": 481,
            "height": 640
          },
          {
            "fileId": "1v3YE29nS2vIWbi_KoA_Ak6eC08WXIgnA",
            "name": "Maple Burl Cookie on Lithe.jpg",
            "width": 640,
            "height": 480
          },
          {
            "fileId": "1n_nrek1LchNXxaPli9TwZyabS2dMkHQN",
            "name": "Maple Burl.jpg",
            "width": 640,
            "height": 481
          },
          {
            "fileId": "1MU-jIes3W7y1hQg4RQzq_PT8v3azXZ0W",
            "name": "Maple Burl Cookie.jpg",
            "width": 640,
            "height": 481
          }
        ],
        "varieties": []
      },
      {
        "name": "Rock Maple",
        "slug": "rock-maple",
        "coverImage": "/images/wood-species/rock-maple-cover.jpg",
        "photoCount": 1,
        "driveFileIds": [
          {
            "fileId": "1BfVXJjvkNYh-nmoAgjRm7bvkTKP_4yD2",
            "name": "Rock Maple with Stones on Pearl.jpg",
            "width": 1227,
            "height": 920
          }
        ],
        "varieties": []
      },
      {
        "name": "Spalted Maple",
        "slug": "spalted-maple",
        "coverImage": "/images/wood-species/spalted-maple-cover.jpg",
        "photoCount": 2,
        "driveFileIds": [
          {
            "fileId": "1qNcR9M2vhRL7LmjuWHbutPCVNUMfiqX9",
            "name": "Spalted Maple Headboard.jpg",
            "width": 1260,
            "height": 945
          },
          {
            "fileId": "1H5smllANfNQIzrkNZu3tq1LVDTMJ0sYH",
            "name": "SM 40 Round Deep Ocean Green 3D Cocktail Wood Arch Interlock.jpg",
            "width": 470,
            "height": 430
          }
        ],
        "varieties": []
      },
      {
        "name": "Sugar Maple",
        "slug": "sugar-maple",
        "coverImage": "/images/wood-species/sugar-maple-cover.heic",
        "photoCount": 1,
        "driveFileIds": [
          {
            "fileId": "1glTiWKqGum61oKiOCinJlUbSOOadOwjt",
            "name": "Sugar Maple with Pacific Blue.HEIC",
            "width": 4032,
            "height": 3024
          }
        ],
        "varieties": []
      },
      {
        "name": "Tiger Maple",
        "slug": "tiger-maple",
        "coverImage": "/images/wood-species/tiger-maple-cover.png",
        "photoCount": 8,
        "driveFileIds": [
          {
            "fileId": "1RPBCdNIyBbuoQ7z0p7AdDxtqf_FHOCUg",
            "name": "Tiger Maple RR.png",
            "width": 1227,
            "height": 920
          },
          {
            "fileId": "1PWIgh0-vsL0bVJ8xXuYvQfXc_UvgxQ0g",
            "name": "6’ Tiger Maple Dining Table.png",
            "width": 1512,
            "height": 2016
          },
          {
            "fileId": "1ylz_FXUO-0F_3Gjs51kxk4fUOP7X8aOS",
            "name": "Tiger maple .png",
            "width": 3020,
            "height": 2817
          },
          {
            "fileId": "1zAtH4oqOvAmn34RTj50cD47_Wp6tHfgz",
            "name": "40” Tiger Maple Crotch(2).png",
            "width": 2016,
            "height": 1512
          },
          {
            "fileId": "1r0_8unte3FsTzl-u1GHMobppQ3so2N8l",
            "name": "6’ Tiger Maple Dining Table(1).png",
            "width": 2016,
            "height": 1512
          },
          {
            "fileId": "1bMZsX38dfe5hbD2aO4jsuPV4NwMQIc56",
            "name": "40” Tiger Maple Crotch(1).png",
            "width": 2016,
            "height": 1512
          },
          {
            "fileId": "1DTde4l-iEVAGVPj9R0UktqAJPQdGuWyo",
            "name": "40” Tiger Maple Crotch.png",
            "width": 1512,
            "height": 2016
          },
          {
            "fileId": "1UF8aOsSCzcmlvnagIfNVAAhrUrH31D5X",
            "name": "40” Tiger Maple Crotch .png",
            "width": 2016,
            "height": 1512
          }
        ],
        "varieties": []
      }
    ]
  },
  {
    "name": "Monkey pod",
    "slug": "monkey-pod",
    "coverImage": "/images/wood-species/monkey-pod-cover.jpg",
    "photoCount": 12,
    "driveFileIds": [
      {
        "fileId": "1E5bvSfJGF-np9oIA_qa7eI8ZGeNup8TW",
        "name": "Monkeypod ocean.jpg",
        "width": 482,
        "height": 640
      },
      {
        "fileId": "1qfksfbbgl8yY6g6TDTiTWmxWJbJZKTI-",
        "name": "Monkeypod and Nokia Black.jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "1CDi6wsssSIcodDKelBw-DDMaPPlObXSd",
        "name": "Monkeypod and Black.jpg",
        "width": 481,
        "height": 640
      },
      {
        "fileId": "16p9Wo8mdA51R6CRhTl8bwv-kDAFuic54",
        "name": "Monkeypod with Onion Green.jpg",
        "width": 3024,
        "height": 4032
      },
      {
        "fileId": "1L6D08l3SQp8XTxIfzA46jcPUmMHZBhMC",
        "name": "Monkeypod and Black.jpg",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1gyoL_GZdWI2UVM1kPaKTHqoiTZhuQDDP",
        "name": "Monkeypod with Black.jpg",
        "width": 3024,
        "height": 4032
      },
      {
        "fileId": "1R8TfUZLWM8Llp0rZ6Y0cwRoQlQZl9U8c",
        "name": "Monkeypod Ocean.jpg",
        "width": 4284,
        "height": 5712
      },
      {
        "fileId": "1xKYX8IGwuEDgFFcP-ArWoKGBfAnEXpu7",
        "name": "Monkey Pod end tables.jpg",
        "width": 1215,
        "height": 911
      },
      {
        "fileId": "14JBhK_AlRYkCIRXECMvOCN4CfnklHOD3",
        "name": "Monkey Pod with Red Black.jpg",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1wpIH2G1F1bx-5uHKAYTYMcohoKkZClCT",
        "name": "IMG_2870.jpg",
        "width": 3024,
        "height": 4032
      },
      {
        "fileId": "1SoMGz40UF0e0ODLzttzO8pfVi_De7uYk",
        "name": "Monkey Pod Red Black.jpg",
        "width": 481,
        "height": 640
      },
      {
        "fileId": "1kXJ6di3_y6qdNTs_j6-cGrgnUvRn2hNE",
        "name": "Monkey Pod with Black Full Pour.jpg",
        "width": 4284,
        "height": 5712
      }
    ],
    "varieties": []
  },
  {
    "name": "Olivewood",
    "slug": "olivewood",
    "coverImage": "/images/wood-species/olivewood-cover.jpg",
    "photoCount": 11,
    "driveFileIds": [
      {
        "fileId": "17tU4Qih6CivKGj-yABmAxmpzC9UCFUjt",
        "name": "Olivewood.jpg",
        "width": 1440,
        "height": 1297
      },
      {
        "fileId": "18iZDKz2p7NpDzBhlFstQYiHEoM_9PF8i",
        "name": "Olivewood Ocean Lagoon.jpg",
        "width": 640,
        "height": 481
      },
      {
        "fileId": "1nOANDgskznqFccT1ilwT2sSHWs602VHV",
        "name": "Olivewood and Black Bistro Table.jpg",
        "width": 709,
        "height": 945
      },
      {
        "fileId": "1mIJyQTOOcKaqNwRBgczrTSISd1qUXl-n",
        "name": "Olivewood Red Black.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1L3IF54UuAo-LESz13ODerZZLvLqKisss",
        "name": "Olivewood Bar tops.jpg",
        "width": 3024,
        "height": 4032
      },
      {
        "fileId": "1J78b4xhTVioiXcp4imKI9VppFjvZkH_F",
        "name": "Olivewood Ocean end table.jpg",
        "width": 960,
        "height": 1280
      },
      {
        "fileId": "1Ei7rIRNOq9-IF8sng7HP2NX3kn4Jub_O",
        "name": "Olivewood and Black.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1JnwGwSJdnnOq52uK53DXaxTqFiSCQXMC",
        "name": "Olivewood Black 2.jpg",
        "width": 481,
        "height": 640
      },
      {
        "fileId": "1zt8qms1i6A0J0f3DWTfmYCEDg6RY-sOK",
        "name": "Olivewood Black.jpg",
        "width": 481,
        "height": 640
      },
      {
        "fileId": "1nZAGJc5B8ehiA1FUcrHXcdcSV-19c8c-",
        "name": "olive ocean.jpg",
        "width": 1920,
        "height": 2560
      },
      {
        "fileId": "1PQuCFe3aHVnXBte_IJk4atzFvg7cpujc",
        "name": "IMG_2003.jpg",
        "width": 960,
        "height": 1280
      }
    ],
    "varieties": []
  },
  {
    "name": "Pine",
    "slug": "pine",
    "coverImage": "/images/wood-species/pine-cover.webp",
    "photoCount": 9,
    "driveFileIds": [
      {
        "fileId": "1_rXt8WKm-T84HVaT8zQm57XtsbN9dSmC",
        "name": "Pine.webp",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1uhUaJ2VC5wvKbBILNRbrRYx6NhySjt-K",
        "name": "Pine with Classic Turned Legs.png",
        "width": 1227,
        "height": 920
      },
      {
        "fileId": "1hyCsRTRDaXen-aYLZ-eBnbGXWmCcgaCK",
        "name": "Pine with RR.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "17Iidkxx44T-5ak2vph4_aV6pJ0zwzeN4",
        "name": "Pine Console.png",
        "width": 1303,
        "height": 977
      },
      {
        "fileId": "1iot-tjFIHtxDpIlJAaQoXSSaPjHDGcNO",
        "name": "7’ Natural Pine Dining Table(2).png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1j_hD7G3At4b15QASKfK0FKlazyG1SUcF",
        "name": "8’ Pine River Dining Table.png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "187ebOP-e4FIKM88lfrOH-XSBwGguN8Dr",
        "name": "Boards Image(93).png",
        "width": 1122,
        "height": 842
      },
      {
        "fileId": "10PPTbbWYJJ-v3wDvC1M5MIDAP3xcY8Er",
        "name": "6’ Pine Bench(1).png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1_07TuvRp0fghGe487s7oNhk_h6txPM1D",
        "name": "8’ Pine River Dining Table .png",
        "width": 1512,
        "height": 2016
      }
    ],
    "varieties": []
  },
  {
    "name": "Rainbow Tulip",
    "slug": "rainbow-tulip",
    "coverImage": "/images/wood-species/rainbow-tulip-cover.jpg",
    "photoCount": 5,
    "driveFileIds": [
      {
        "fileId": "1_qOzXs4pHc54ozI5zvKUl_6gtOJoWoJj",
        "name": "Rainbow Tulip Ocean.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1e_Fk4iyM1mNbFDCbbqm7GEOQeHr2OtnS",
        "name": "Rainbow Tulip with Copper.jpg",
        "width": 1445,
        "height": 1920
      },
      {
        "fileId": "1DHBRFeR81MC9M5uoEuJ5r5rDrsGQqLaD",
        "name": "Rainbow Tulip with Green Onion fill.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1Le-8nQOiSpHS7whBeU7C6loitF7X_R1d",
        "name": "Rainbow Tulip Coffee Table.jpg",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1V6cnTuPH5yC3HRhAZdct3p0TINOaiB5V",
        "name": "Rainbow Tulip.jpg",
        "width": 1920,
        "height": 3863
      }
    ],
    "varieties": []
  },
  {
    "name": "Red Oak",
    "slug": "red-oak",
    "coverImage": "/images/wood-species/red-oak-cover.jpg",
    "photoCount": 2,
    "driveFileIds": [
      {
        "fileId": "1pSlPhv4GCPwZLMw8L_9fyUJnBwiCooaC",
        "name": "IMG_0942.jpg",
        "width": 683,
        "height": 911
      },
      {
        "fileId": "1uDmVFLGcJXhUeoRFLmsy18VMY0UlNSN4",
        "name": "Red oak ocean.jpg",
        "width": 481,
        "height": 640
      }
    ],
    "varieties": []
  },
  {
    "name": "Redwood",
    "slug": "redwood",
    "coverImage": "/images/wood-species/redwood-cover.png",
    "photoCount": 6,
    "driveFileIds": [
      {
        "fileId": "1WJcPlcZicpq2ND83vIuS6dOHl69uebkQ",
        "name": "Redwood with Angel Blue 3D.png",
        "width": 768,
        "height": 1024
      },
      {
        "fileId": "1CTXLmDwgo9g9F3rYojd0OYPBJ5eQKNBj",
        "name": "Redwood with Emerald Green River.png",
        "width": 2572,
        "height": 2981
      },
      {
        "fileId": "13YBVEYcw6sVj3SqxcekqoXvfuV8HnvDJ",
        "name": "Redwood with Rocks on Pearl.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1QIrCANr1RVJ8ZQLuojO0yMzXn0bpLOIe",
        "name": "Redwood and Resin End Table(1).png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1DY1-Otz0MmJ7D88-f4kUq30Z-7O3od8L",
        "name": "6’ Redwood River Dining Table.png",
        "width": 2016,
        "height": 1512
      },
      {
        "fileId": "1dzXXdkV0eqy7mZQZP7qy-GC_w34zLDVU",
        "name": "Redwood River .png",
        "width": 2016,
        "height": 1512
      }
    ],
    "varieties": []
  },
  {
    "name": "Sassafras",
    "slug": "sassafras",
    "coverImage": "/images/wood-species/sassafras-cover.heic",
    "photoCount": 3,
    "driveFileIds": [
      {
        "fileId": "1UN9Kd4nYzstWsDEVSmiN9u4zZV8qWyko",
        "name": "Sassafras Black Pebbles.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "13Ev9zJida4qn5_o0a78y-WNneqPASLM7",
        "name": "Sassafras RR on Pacific Blue.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1wBSbWfVxJr6O-2d7Cckn3KAY0n7c7w4y",
        "name": "Sassafrass and Angel Blue.HEIC",
        "width": 4032,
        "height": 3024
      }
    ],
    "varieties": []
  },
  {
    "name": "Sycamore",
    "slug": "sycamore",
    "coverImage": "/images/wood-species/sycamore-cover.jpg",
    "photoCount": 5,
    "driveFileIds": [
      {
        "fileId": "1S8l5d4WV25Xqc5HI0AdaaoNy8_fLXDBN",
        "name": "Sycamore slab.jpg",
        "width": 640,
        "height": 481
      },
      {
        "fileId": "12STO-EUVxItrxGrZWrEBBLQHZAUvK6vs",
        "name": "Sycamore Elipse.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "1spOBZdnQlHoB3zwZaJwE4o8-uVtBjegw",
        "name": "Sycamore 72x35 with bias cuts.jpg",
        "width": 1440,
        "height": 1920
      },
      {
        "fileId": "1awQJBhQkbSyxDbzwB9h7ynmWN3XZbRRE",
        "name": "68080761957__255AA69B-3B6C-4D8F-8E9A-40C65025BA36.HEIC",
        "width": 4032,
        "height": 3024
      },
      {
        "fileId": "15zTjO6A9lwaBHNq5mC9FMZ9tyDj7D_aK",
        "name": "Sycamore Elipse.HEIC",
        "width": 4032,
        "height": 3024
      }
    ],
    "varieties": []
  },
  {
    "name": "Tulip Wood",
    "slug": "tulip-wood",
    "coverImage": "/images/wood-species/tulip-wood-cover.png",
    "photoCount": 1,
    "driveFileIds": [
      {
        "fileId": "1-eDMEuechNPStbmaEnWDaeTaEsozUEGM",
        "name": "6’ Tulipwood Dining Table(1).png",
        "width": 2016,
        "height": 1512
      }
    ],
    "varieties": []
  },
  {
    "name": "White Oak",
    "slug": "white-oak",
    "coverImage": "/images/wood-species/white-oak-cover.jpg",
    "photoCount": 1,
    "driveFileIds": [
      {
        "fileId": "1PW6tsX6Zogd9LbCariaqY5rYNnpWiVYz",
        "name": "White Oak 96x45 Black 3D (1).jpg",
        "width": 3024,
        "height": 4032
      }
    ],
    "varieties": []
  },
  {
    "name": "Willow",
    "slug": "willow",
    "coverImage": "/images/wood-species/willow-cover.jpg",
    "photoCount": 1,
    "driveFileIds": [
      {
        "fileId": "1Tl_zrC2Fa2-H56G0PwxGt_GaTlumWDgo",
        "name": "Black WILLOW Round Midnight Blue 3D.jpg",
        "width": 481,
        "height": 640
      }
    ],
    "varieties": []
  }
]
